questions:
    1:
        id : 1
        content : content
        type : closed
        answer : A
        points : 1
    2:
        id : 2
        content : content
        type : closed
        answer : C
        points : 1
    3:
        id : 3
        content : content
        type : closed
        answer : C
        points : 2
    4:
        id : 4
        content : content
        type : closed
        answer : B
        points : 2
    5:
        id : 5
        content : content
        type : closed
        answer : C
        points : 1
    6:
        id : 6
        content : content
        type : closed
        answer : A
        points : 1
    7:
        id : 7
        content : content
        type : closed
        answer : D
        points : 1
    8:
        id : 8
        content : content
        type : closed
        answer : C
        points : 1
    9:
        id : 9
        content : content
        type : closed
        answer : D
        points : 1
    10:
        id : 10
        content : content
        type : closed
        answer : A
        points : 2
    11:
        id : 11
        content : content
        type : closed
        answer : A
        points : 2
    12:
        id : 12
        content : content
        type : closed
        answer : D
        points : 1
    13:
        id : 13
        content : content
        type : closed
        answer : A B C D E F
        points : 2
    14:
        id : 14
        content : content
        type : closed
        answer : B
        points : 1
    15:
        id : 15
        content : content
        type : closed
        answer : D
        points : 1
    16:
        id : 16
        content : content
        type : closed
        answer : C
        points : 1
    17:
        id : 17
        content : content
        type : closed
        answer : A
        points : 1
    18:
        id : 18
        content : content
        type : closed
        answer : B C D
        points : 2
    19:
        id : 19
        content : content
        type : closed
        answer : A
        points : 1
    20:
        id : 20
        content : content
        type : closed
        answer : D
        points : 1
    21:
        id : 21
        content : content
        type : closed
        answer : B
        points : 1
    22:
        id : 22
        content : content
        type : closed
        answer : A
        points : 2
    23:
        id : 23
        content : content
        type : closed
        answer : B
        points : 3
    24:
        id : 24
        content : content
        type : closed
        answer : D
        points : 1
    25:
        id : 25
        content : content
        type : closed
        answer : D
        points : 1
    26:
        id : 26
        content : content
        type : closed
        answer : C
        points : 1
    27:
        id : 27
        content : content
        type : closed
        answer : B
        points : 1
    28:
        id : 28
        content : content
        type : closed
        answer : B
        points : 1
    29:
        id : 29
        content : content
        type : closed
        answer : D
        points : 1
    30:
        id : 30
        content : content
        type : closed
        answer : C
        points : 1
    31:
        id : 31
        content : content
        type : closed
        answer : B
        points : 1
    32:
        id : 32
        content : content
        type : closed
        answer : D
        points : 1
    33:
        id : 33
        content : content
        type : closed
        answer : B
        points : 1
    34:
        id : 34
        content : content
        type : closed
        answer : D
        points : 2
    35:
        id : 35
        content : content
        type : closed
        answer : A
        points : 1
    36:
        id : 36
        content : content
        type : closed
        answer : B
        points : 1
    37:
        id : 37
        content : content
        type : closed
        answer : E
        points : 3
    38:
        id : 38
        content : content
        type : closed
        answer : D
        points : 1
    39:
        id : 39
        content : content
        type : closed
        answer : C
        points : 1
    40:
        id : 40
        content : content
        type : closed
        answer : B
        points : 2
    41:
        id : 41
        content : content
        type : closed
        answer : D
        points : 1
    42:
        id : 42
        content : content
        type : closed
        answer : B
        points : 1
    43:
        id : 43
        content : content
        type : closed
        answer : B
        points : 1
    44:
        id : 44
        content : content
        type : open
        points : 2
    45:
        id : 45
        content : content
        type : open
        points : 2
    46:
        id : 46
        content : content
        type : open
        points : 2
    47:
        id : 47
        content : content
        type : open
        points : 2
    48:
        id : 48
        content : content
        type : open
        points : 2
    49:
        id : 49
        content : content
        type : open
        points : 3
    50:
        id : 50
        content : content
        type : open
        points : 5

